
const codeLines=["public class Solution","{","    public double FindMedianSortedArrays(int[] nums1, int[] nums2)","    {","        if (nums1.Length > nums2.Length)","        {","            return FindMedianSortedArrays(nums2, nums1);","        }","","        int m = nums1.Length;","        int n = nums2.Length;","        int left = 0;","        int right = m;","","        while (left <= right)","        {","            int i = (left + right) / 2;","            int j = (m + n + 1) / 2 - i;","","            int nums1Left = (i == 0) ? int.MinValue : nums1[i - 1];","            int nums1Right = (i == m) ? int.MaxValue : nums1[i];","            int nums2Left = (j == 0) ? int.MinValue : nums2[j - 1];","            int nums2Right = (j == n) ? int.MaxValue : nums2[j];","","            if (nums1Left <= nums2Right && nums2Left <= nums1Right)","            {","                if ((m + n) % 2 == 1)","                {","                    return Math.Max(nums1Left, nums2Left);","                }","","                return (Math.Max(nums1Left, nums2Left) +","                        Math.Min(nums1Right, nums2Right)) / 2.0;","            }","","            if (nums1Left > nums2Right)","            {","                right = i - 1;","            }","            else","            {","                left = i + 1;","            }","        }","","        return 0;","    }","}"];
const $=id=>document.getElementById(id);const el={nums1:$("nums1Input"),nums2:$("nums2Input"),len1:$("len1Input"),len2:$("len2Input"),random:$("randomBtn"),sample:$("sampleBtn"),build:$("buildBtn"),play:$("playBtn"),step:$("stepBtn"),reset:$("resetBtn"),speed:$("speedRange"),speedValue:$("speedValue"),error:$("errorBox"),stepList:$("stepList"),arrayA:$("arrayA"),arrayB:$("arrayB"),cutValue:$("cutValue"),cutSub:$("cutSub"),leftCount:$("leftCountValue"),targetLeft:$("targetLeftCount"),compareValue:$("compareValue"),compareSub:$("compareSub"),medianValue:$("medianValue"),medianSub:$("medianSub"),formula:$("formulaBox"),stepExplain:$("stepExplain"),beginner:$("beginnerExplain"),resultBig:$("resultBig"),resultExplain:$("resultExplain"),codeBlock:$("codeBlock"),codeExplain:$("codeExplain"),simple:$("simpleModeBtn"),pro:$("proModeBtn"),modeHint:$("modeHint")};
let state={steps:[],index:0,timer:null,mode:"simple"};
function parseArray(text){const t=text.trim();if(t==="")return[];const nums=t.split(",").map(x=>x.trim()).filter(Boolean).map(x=>{if(!/^-?\d+$/.test(x))throw new Error("Only integers are allowed.");return Number(x);});for(let i=1;i<nums.length;i++){if(nums[i]<nums[i-1])throw new Error("Arrays must be sorted.");}return nums;}
function randomSortedArray(length){const arr=[];let cur=Math.floor(Math.random()*4)-2;for(let i=0;i<length;i++){cur+=Math.floor(Math.random()*4);arr.push(cur);}return arr;}
function arrText(arr){return arr.join(", ");}
function fmt(v){if(v===Number.NEGATIVE_INFINITY)return"-inf";if(v===Number.POSITIVE_INFINITY)return"+inf";return String(v);} 
function buildSteps(raw1,raw2){let a=raw1.slice(),b=raw2.slice(),swapped=false;const steps=[];if(a.length>b.length){[a,b]=[b,a];swapped=true;}const m=a.length,n=b.length,leftTarget=Math.floor((m+n+1)/2);if(m===0&&n===0)throw new Error("At least one array must be non-empty.");if(swapped)steps.push({phase:"swap",a,b,leftTarget,swapped});let left=0,right=m;while(left<=right){const i=Math.floor((left+right)/2),j=leftTarget-i;const Aleft=i===0?Number.NEGATIVE_INFINITY:a[i-1],Aright=i===m?Number.POSITIVE_INFINITY:a[i],Bleft=j===0?Number.NEGATIVE_INFINITY:b[j-1],Bright=j===n?Number.POSITIVE_INFINITY:b[j];const valid=Aleft<=Bright&&Bleft<=Aright,goLeft=Aleft>Bright,odd=(m+n)%2===1,median=valid?(odd?Math.max(Aleft,Bleft):(Math.max(Aleft,Bleft)+Math.min(Aright,Bright))/2):null;steps.push({phase:valid?(odd?"foundOdd":"foundEven"):(goLeft?"moveLeft":"moveRight"),a,b,leftTarget,swapped,i,j,Aleft,Aright,Bleft,Bright,valid,goLeft,odd,median});if(valid)break;if(goLeft)right=i-1;else left=i+1;}return steps;}
function codeInfo(step){if(step.phase==="swap")return{lines:[5,6,7,8],text:"First make nums1 the shorter array."};if(step.phase==="moveLeft")return{lines:[15,17,18,20,21,22,23,35,36,37,38],text:"i is too large, so right = i - 1."};if(step.phase==="moveRight")return{lines:[15,17,18,20,21,22,23,39,40,41],text:"i is too small, so left = i + 1."};if(step.phase==="foundOdd")return{lines:[15,17,18,20,21,22,23,25,26,27,28,29],text:"Valid cut found. Odd length returns left max."};return{lines:[15,17,18,20,21,22,23,25,31,32,33],text:"Valid cut found. Even length returns average."};}
function stepMeta(step,index,total){if(step.phase==="swap")return{title:`Step ${index+1} / ${total}`,desc:"Preprocess: place the shorter array on top."};let desc=`Try cut i=${step.i}, j=${step.j}.`;if(step.valid)desc+=" Valid cut found.";else if(step.goLeft)desc+=` Aleft=${fmt(step.Aleft)} > Bright=${fmt(step.Bright)}, so move left.`;else desc+=` Bleft=${fmt(step.Bleft)} > Aright=${fmt(step.Aright)}, so move right.`;return{title:`Step ${index+1} / ${total}`,desc};}
function beginnerText(step){if(step.phase==="swap")return"先把短数组放在上面，因为后面只在它身上做二分。";if(step.valid)return step.odd?`这次已经切对了。总长度是奇数，所以答案就是左边最大的那个数：${Math.max(step.Aleft,step.Bleft)}。`:`这次已经切对了。总长度是偶数，所以看左边最大和右边最小：${Math.max(step.Aleft,step.Bleft)} 和 ${Math.min(step.Aright,step.Bright)}。`;if(step.goLeft)return`这刀切得太靠右，因为 ${fmt(step.Aleft)} 比 ${fmt(step.Bright)} 还大。`;return`这刀切得太靠左，因为 ${fmt(step.Bleft)} 比 ${fmt(step.Aright)} 还大。`;}
function formulaText(step){if(step.phase==="swap")return"先保证 m <= n，然后只在短数组上二分。";return`左边元素个数固定为 (m+n+1)/2 = ${step.leftTarget}；当前边界是 Aleft=${fmt(step.Aleft)}、Aright=${fmt(step.Aright)}、Bleft=${fmt(step.Bleft)}、Bright=${fmt(step.Bright)}。`;}
function renderCode(lines,text){el.codeBlock.innerHTML="";const set=new Set(lines);codeLines.forEach((line,idx)=>{const row=document.createElement("div");row.className="cline";if(set.size>0)row.classList.add(set.has(idx+1)?"active":"dim");row.innerHTML=`<div class="no">${idx+1}</div><div>${line||" "}</div>`;el.codeBlock.appendChild(row);});el.codeExplain.textContent=text;}
function renderArray(container,arr,cut,focusL,focusR){container.innerHTML="";for(let b=0;b<=arr.length;b++){const divider=document.createElement("div");divider.className="boundary"+(b===cut?" active":"");container.appendChild(divider);if(b===arr.length)continue;const cell=document.createElement("div");cell.className="cell "+(b<cut?"left":"right");cell.dataset.index=b;if(b===focusL)cell.classList.add("focusL");if(b===focusR)cell.classList.add("focusR");cell.innerHTML=`<div class="num">${arr[b]}</div>`;container.appendChild(cell);}}
function renderSteps(){el.stepList.innerHTML="";state.steps.forEach((s,i)=>{const m=stepMeta(s,i,state.steps.length);const item=document.createElement("div");item.className="step"+(i===state.index?" active":"");item.innerHTML=`<div class="step-title">${m.title}</div><div class="step-desc">${m.desc}</div>`;el.stepList.appendChild(item);});}
function resetView(){el.stepList.innerHTML="";el.arrayA.innerHTML="";el.arrayB.innerHTML="";el.cutValue.textContent="i = -, j = -";el.cutSub.textContent="先生成步骤";el.leftCount.textContent="-";el.targetLeft.textContent="-";el.compareValue.textContent="-";el.compareSub.textContent="等待步骤";el.medianValue.textContent="-";el.medianSub.textContent="找到合法切分后出现";el.formula.innerHTML="左边元素总数固定为 (m + n + 1) / 2。合法切分条件是 Aleft <= Bright 且 Bleft <= Aright。";el.stepExplain.textContent="生成步骤后查看。";el.beginner.textContent="这里会用更口语的话解释当前这一步。";el.resultBig.textContent="-";el.resultExplain.textContent="奇数取左边最大，偶数取平均。";renderCode([],"This box explains why the highlighted code is running.");}
function renderCurrent(){if(!state.steps.length)return;const s=state.steps[state.index];renderSteps();if(s.phase==="swap"){renderArray(el.arrayA,s.a,0,-1,0);renderArray(el.arrayB,s.b,0,-1,0);el.cutValue.textContent="预处理";el.cutSub.textContent="先让上面的数组更短";el.leftCount.textContent="-";el.targetLeft.textContent=String(s.leftTarget);el.compareValue.textContent="-";el.compareSub.textContent="下一步开始试切点";el.medianValue.textContent="-";el.medianSub.textContent="找到合法切分后出现";el.resultBig.textContent="-";el.resultExplain.textContent="这里只是预处理。";}else{renderArray(el.arrayA,s.a,s.i,s.i-1,s.i);renderArray(el.arrayB,s.b,s.j,s.j-1,s.j);el.cutValue.textContent=`i = ${s.i}, j = ${s.j}`;el.cutSub.textContent=s.swapped?"已自动交换输入，当前上方是较短数组":"当前上方本来就是较短数组";el.leftCount.textContent=String(s.i+s.j);el.targetLeft.textContent=String(s.leftTarget);el.compareValue.textContent=`${fmt(s.Aleft)} <= ${fmt(s.Bright)} / ${fmt(s.Bleft)} <= ${fmt(s.Aright)}`;if(s.valid){el.compareSub.textContent="两组比较都成立";el.medianValue.textContent=String(s.median);el.medianSub.textContent=s.odd?"奇数：取左边最大":"偶数：取平均";el.resultBig.textContent=String(s.median);el.resultExplain.textContent=el.medianSub.textContent;}else if(s.goLeft){el.compareSub.textContent="i 太大，要往左";el.medianValue.textContent="-";el.medianSub.textContent="继续找";el.resultBig.textContent="-";el.resultExplain.textContent="短数组左边拿太多了。";}else{el.compareSub.textContent="i 太小，要往右";el.medianValue.textContent="-";el.medianSub.textContent="继续找";el.resultBig.textContent="-";el.resultExplain.textContent="短数组左边拿太少了。";}}el.formula.innerHTML=state.mode==="simple"?`Current core rule: <strong>${formulaText(s)}</strong>`:formulaText(s);el.stepExplain.textContent=stepMeta(s,state.index,state.steps.length).desc;el.beginner.textContent=beginnerText(s);const info=codeInfo(s);renderCode(info.lines,info.text);}
function stopPlay(){if(state.timer!==null){clearInterval(state.timer);state.timer=null;el.play.textContent="自动播放";}}
function build(){stopPlay();el.error.textContent="";try{state.steps=buildSteps(parseArray(el.nums1.value),parseArray(el.nums2.value));state.index=0;renderCurrent();}catch(err){state.steps=[];state.index=0;el.error.textContent=err.message;resetView();}}
function nextStep(){if(!state.steps.length){build();if(!state.steps.length)return;}if(state.index<state.steps.length-1){state.index+=1;renderCurrent();}else stopPlay();}
function resetStep(){stopPlay();if(!state.steps.length){build();return;}state.index=0;renderCurrent();}
function togglePlay(){if(!state.steps.length){build();if(!state.steps.length)return;}if(state.timer!==null){stopPlay();return;}el.play.textContent="暂停";state.timer=setInterval(()=>{if(state.index>=state.steps.length-1){stopPlay();return;}nextStep();},Number(el.speed.value));}
function setMode(mode){state.mode=mode;el.simple.classList.toggle("active",mode==="simple");el.pro.classList.toggle("active",mode==="pro");el.modeHint.textContent=mode==="simple"?"当前会优先用口语解释。":"当前会优先用更紧凑的公式解释。";if(state.steps.length)renderCurrent();}
el.random.addEventListener("click",()=>{const a=Math.max(0,Math.min(12,Number(el.len1.value)||0)),b=Math.max(0,Math.min(12,Number(el.len2.value)||0));if(a===0&&b===0){el.error.textContent="At least one array length must be greater than 0.";return;}el.nums1.value=arrText(randomSortedArray(a));el.nums2.value=arrText(randomSortedArray(b));build();});
el.sample.addEventListener("click",()=>{el.nums1.value="1, 2";el.nums2.value="3, 4";build();});
el.build.addEventListener("click",build);el.play.addEventListener("click",togglePlay);el.step.addEventListener("click",nextStep);el.reset.addEventListener("click",resetStep);el.simple.addEventListener("click",()=>setMode("simple"));el.pro.addEventListener("click",()=>setMode("pro"));el.speed.addEventListener("input",()=>{el.speedValue.textContent=`${el.speed.value}ms`;if(state.timer!==null){stopPlay();togglePlay();}});resetView();build();

